-- Original placeholder sprite data made for this repository.
-- Each character maps to a palette entry in src/assets.lua.

return {
    hero_down = {
        "........",
        "..HHHH..",
        ".HFFFFH.",
        ".HFEEFH.",
        "..FFFF..",
        "..BBBB..",
        ".BBBBBB.",
        ".BBCCBB.",
        "..BBBB..",
        "..L..L..",
        ".LL..LL.",
        "........",
    },
    hero_up = {
        "........",
        "..HHHH..",
        ".HHHHHH.",
        ".HHHHHH.",
        "..FFFF..",
        "..BBBB..",
        ".BBBBBB.",
        ".BBCCBB.",
        "..BBBB..",
        "..L..L..",
        ".LL..LL.",
        "........",
    },
    hero_left = {
        "........",
        "..HHHH..",
        ".HFFFF..",
        ".HFEEF..",
        "..FFFF..",
        "..BBBB..",
        ".BBBBB..",
        ".BBCBB..",
        "..BBBB..",
        "..L..L..",
        ".LL..LL.",
        "........",
    },
    hero_right = {
        "........",
        "..HHHH..",
        "..FFFFH.",
        "..FEEFH.",
        "..FFFF..",
        "..BBBB..",
        "..BBBBB.",
        "..BBCBB.",
        "..BBBB..",
        "..L..L..",
        ".LL..LL.",
        "........",
    },
    friend = {
        "........",
        "..PPPP..",
        ".PPPPPP.",
        ".PPEEPP.",
        "..PPPP..",
        "..GGGG..",
        ".GGGGGG.",
        ".GGWWGG.",
        "..GGGG..",
        "..L..L..",
        ".LL..LL.",
        "........",
    },
    dummy = {
        "........",
        "...YY...",
        "..YYYY..",
        "..YEEY..",
        "..YYYY..",
        "...YY...",
        "..OOOO..",
        ".OOOOOO.",
        ".OOOOOO.",
        "...OO...",
        "...OO...",
        "........",
    },
    enemy = {
        "................",
        ".....WWWW.......",
        "...WWWWWWWW.....",
        "..WWKWWWWKWW....",
        "..WWWWWWWWWW....",
        "...WWWWWWWW.....",
        "....WOOOOOW.....",
        "...WOOOOOOOW....",
        "..WOOOOOOOOOW...",
        "..WOOOWWOOOOW...",
        "...OOOOOOOOO....",
        "....OO....OO....",
        "...OO......OO...",
        "................",
    },
}
